[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "topology_scrambler"
maintainers = [{ name = "Andrew Tarzia", email = "andrew.tarzia@gmail.com" }]
dependencies = ["cgexplore==2025.2.5.1"]
requires-python = ">=3.11"
dynamic = ["version"]
readme = "README.md"

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy",
    "pip-tools",
    # TODO: Remove pin when https://github.com/TvoroG/pytest-lazy-fixture/issues/65 is resolved.
    # pytest-lazy-fixture 0.6.0 is incompatible with pytest 8.0.0
    "pytest<8",
    "pytest-datadir",
    "pytest-lazy-fixture",
    "pytest-cov",
]

[project.scripts]
write_chemiscope = "model_enumeration.write_chemiscope:main"
mgen_crest_analysis = "model_enumeration.mgen_crest_analysis:main"
mgen_genetic = "model_enumeration.mgen_genetic:main"
mgen_cs1 = "model_enumeration.mgen_cs1:main"
mgen_cs2 = "model_enumeration.mgen_cs2:main"
mgen_cs3 = "model_enumeration.mgen_cs3:main"
mgen_cs4 = "model_enumeration.mgen_cs4:main"
mgen_cs6 = "model_enumeration.mgen_cs6:main"
mgen_star = "model_enumeration.mgen_star:main"
validation_mnl2n = "model_enumeration.validation_mnl2n:main"


[project.urls]
github = "https://github.com/andrewtarzia/topology_scrambler"

[tool.setuptools_scm]
write_to = "src/_version.py"

[tool.setuptools.packages.find]
where = [
    # list of folders that contain the packages (["."] by default)
    "src",
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ANN401", "COM812", "ISC001", "FBT001", "FBT002"]

[tool.ruff.lint.pydocstyle]
convention = "google"


[tool.mypy]
show_error_codes = true
implicit_optional = false
warn_no_return = true
strict_optional = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_unreachable = true
disallow_any_generics = false

[[tool.mypy.overrides]]
module = [
    "rdkit.*",
    "scipy.*",
    "pytest_lazyfixture.*",
    "pathos.*",
    "matplotlib.*",
    "pandas.*",
    "seaborn.*",
    "mchammer.*",
    "spindry.*",
    "pymongo.*",
    "vabene.*",
    "setuptools.*",
    "stk.*",
    "networkx.*",
    "openbabel.*",
    "MDAnalysis.*",
    "atomlite.*",
]
ignore_missing_imports = true
